### ISSUE TITLE
Requirement list

### ISSUE THREAD

**Issue by kOoLiNuS** [berkgoksel/Elayv#2]
Hi!
I've downloaded the script and tried launching it via Terminal.app on a vanilla macOS Catalina. The system tells me this:

```me@machineo Desktop %python ./elayv.py 
Traceback (most recent call last):
  File "./elayv.py", line 2, in <module>
    import urllib.request
ImportError: No module named request
```

Then I saw it was adapted to use Python 3 and:

```me@machineo Desktop % python3 ./elayv.py
Traceback (most recent call last):
  File "./elayv.py", line 8, in <module>
    import netaddr
ModuleNotFoundError: No module named 'netaddr'
```

Can you help?

**Comment by berkgoksel** [comment]
Sorry for the late reply, this repo was not actively managed. Yes, the script uses the netaddr module. I have updated the repo so you can install it using 

> pip3 install -r requirements.txt
